-- phpMyAdmin SQL Dump
-- version 3.2.4
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Apr 13, 2014 at 12:36 
-- Server version: 5.1.41
-- PHP Version: 5.3.1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `museos`
--

-- --------------------------------------------------------

--
-- Table structure for table `categoria`
--

CREATE TABLE IF NOT EXISTS `categoria` (
  `id_categ` int(3) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) NOT NULL,
  `estado` varchar(50) NOT NULL,
  PRIMARY KEY (`id_categ`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=8 ;

--
-- Dumping data for table `categoria`
--

INSERT INTO `categoria` (`id_categ`, `nombre`, `estado`) VALUES
(1, 'Historia', 'habilitado'),
(2, 'Historia Militar', 'habilitado'),
(3, 'Arqueologia , antropologia y etnologia', 'habilitado'),
(4, 'Ciencia y tecnologia', 'habilitado'),
(5, 'Arte', 'habilitado'),
(6, 'Religioso', 'habilitado');

-- --------------------------------------------------------

--
-- Table structure for table `museo`
--

CREATE TABLE IF NOT EXISTS `museo` (
  `Id` int(2) DEFAULT NULL,
  `id_categ` int(1) DEFAULT NULL,
  `Nombre` varchar(83) DEFAULT NULL,
  `acerca` varchar(4000) NOT NULL,
  `Ubicacion` varchar(25) DEFAULT NULL,
  `Direccion` varchar(98) DEFAULT NULL,
  `Horario` varchar(75) DEFAULT NULL,
  `Costo` varchar(39) DEFAULT NULL,
  `Telefono` varchar(20) DEFAULT NULL,
  `Correo` varchar(74) DEFAULT NULL,
  `Web` varchar(113) DEFAULT NULL,
  `url` varchar(1330) DEFAULT NULL,
  `imagen` varchar(100) NOT NULL,
  `estado` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `museo`
--

INSERT INTO `museo` (`Id`, `id_categ`, `Nombre`, `acerca`, `Ubicacion`, `Direccion`, `Horario`, `Costo`, `Telefono`, `Correo`, `Web`, `url`, `imagen`, `estado`) VALUES
(1, 1, 'Casa de la Gatronomía Peruana', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Conde de Superunda 170', 'Mar-Dom de 9am- 5pm', 'Ingreso Libre', '4267264', 'direccion_museos@mcultura.gob.pe aleon@mcultura.gob.pe', '', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.044378,-77.031525&amp;aq=&amp;sll=-12.046107,-77.035476&amp;sspn=0.001377,0.002336&amp;ie=UTF8&amp;ll=-12.044378,-77.031525&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14&amp;output=embed"></iframe>', 'large/Casa de la Gatronomía Peruana.jpg', 'habilitado'),
(2, 1, 'Casa de la Literatura Peruana', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Ancash 207', 'Mar-Dom de 10:30 am -  7:00pm', 'Ingreso Libre', '4262573', 'casadelaliteratura@gmail.com', 'www.casadelaliteratura.gob.pe', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.04437,-77.028816&amp;aq=&amp;sll=-12.044378,-77.028816&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.04437,-77.028816&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.04437,-77.028816&amp;aq=&amp;sll=-12.044378,-77.028816&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.04437,-77.028816" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Casa de la Literatura Peruana.jpg', 'habilitado'),
(3, 1, 'Casa Museo Bodega y Quadra', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Ancash  Lima  209-217', 'Mar-Dom de 9am- 5pm', 'Ingreso Libre', '4270675', 'mfhon@emilima.cm.pe', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.044493,-77.028441&amp;aq=&amp;sll=-12.04437,-77.028816&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.044378,-77.028816&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.044493,-77.028441&amp;aq=&amp;sll=-12.04437,-77.028816&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.044378,-77.028816&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Casa Museo Bodega y Quadra.jpg', 'habilitado'),
(4, 1, 'Museo Casa José Carlos Mariátegui', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Washington 1946', 'Mar-Vier 9-1 y de 2-5:45/Sábado 9-1 p.m.', 'Ingreso Libre', '3306074', 'casamariategui@mcultura.gob.pe', 'http://mariategui.org', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.063875,-77.038952&amp;aq=&amp;sll=-12.044483,-77.028451&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.063875,-77.038952&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.063875,-77.038952&amp;aq=&amp;sll=-12.044483,-77.028451&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.063875,-77.038952" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', '/large/Museo Casa José Carlos Mariátegui.jpg', 'habilitado'),
(5, 1, 'Museo de Sitio Cerro San Cristóbal', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Cerro San Cristóbal', 'Lun -Dom 9-6 p.m.', 'Adulto 5 y escolar 1', '7131358', 'Ministerio de Cultura', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.035378,-77.017908&amp;aq=&amp;sll=-12.063875,-77.038952&amp;sspn=0.011016,0.01869&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.035378,-77.017908&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.035378,-77.017908&amp;aq=&amp;sll=-12.063875,-77.038952&amp;sspn=0.011016,0.01869&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.035378,-77.017908" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Museo de Sitio Cerro San Cristóbal.jpg', 'habilitado'),
(6, 1, 'Museo Combatientes del Morro de Arica', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Cailloma 125', 'Lun -Vier 9-3 Sáb de 9 -1', 'Adulto 3 Estudiante 2 Extranjero 5', '4270958', 'bolognesi.museos@hotmail.com', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.046747,-77.034803&amp;aq=&amp;sll=-12.035378,-77.017908&amp;sspn=0.011018,0.01869&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.046747,-77.034803&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.046747,-77.034803&amp;aq=&amp;sll=-12.035378,-77.017908&amp;sspn=0.011018,0.01869&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.046747,-77.034803" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Museo Combatientes del Morro de Arica.jpg', 'habilitado'),
(7, 1, 'Museo de la Compañía de Bomberos "La Salvadora" Lima 10', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. de la Unión 1027', 'Lun-Dom 8 a.m.-8 p.m.', 'Ingreso Libre', '4280288', 'rigcavi@hotmail.com', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.052305,-77.035444&amp;aq=&amp;sll=-12.046747,-77.034803&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.046749,-77.034802&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.052305,-77.035444&amp;aq=&amp;sll=-12.046747,-77.034803&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.046749,-77.034802&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Museo de la Compañía de Bomberos "La Salvadora" Lima 10.jpg', 'deshabilitado'),
(8, 1, 'Museo Electoral y de la  Democracia', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Av. Nicolás de Piérola 1070', 'Lun-Ver 8-4', 'Ingreso Libre', '3111700 Anexo 2031', 'museoelectoral@jne.gob.pe', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.052295,-77.033566&amp;aq=&amp;sll=-12.05231,-77.035446&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.05231,-77.035446&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.052295,-77.033566&amp;aq=&amp;sll=-12.05231,-77.035446&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.05231,-77.035446&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Museo Electoral y de la  Democracia.jpg', 'habilitado'),
(9, 1, 'Museo Gráfico el Peruano', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Quilca 556', 'Lun -Vier 9-5', 'Ingreso Libre', '3150400 Anexo 2210', '-', 'www.editoraperu.com.pe', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.050765,-77.042217&amp;aq=&amp;sll=-12.052289,-77.033558&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.052289,-77.033558&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.050765,-77.042217&amp;aq=&amp;sll=-12.052289,-77.033558&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.052289,-77.033558&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Museo Gráfico el Peruano.jpg', 'habilitado'),
(10, 1, 'Museo de la Identificación - RENIEC', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Av. Bolivia 144. Torre II, piso 2º. Centro Cívico de Lima', 'Lun -Dom 9-5', 'Ingreso Libre', '3152700 Anexo 1158', 'museo@reniec.gob.pe', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.056072,-77.037166&amp;aq=&amp;sll=-12.050758,-77.042227&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.050758,-77.042227&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.056072,-77.037166&amp;aq=&amp;sll=-12.050758,-77.042227&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.050758,-77.042227&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Museo de la Identificación - RENIEC.jpg', 'habilitado'),
(11, 1, 'Museo del Congreso y de  la Inquisición', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Junín 548', 'Lun-Viern 9-5', 'Ingreso Libre', '3117777', 'museo@congreso.com.pe', 'www.congreso.gob.pe', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.048208,-77.02644&amp;aq=&amp;sll=-12.056067,-77.037163&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.056067,-77.037163&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.048208,-77.02644&amp;aq=&amp;sll=-12.056067,-77.037163&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.056067,-77.037163&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', '', ''),
(12, 1, 'Museo Metropolitano de Lima', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Av. 28 de Julio con Av. Garcilaso de la Vega', 'Mar -Dom9-5', 'Tarifa general S/: 4', '4337122', '', 'https://www.facebook.com/pages/Museo-Metropolitano-de-Lima/223846547692079', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.063568,-77.03681&amp;aq=&amp;sll=-12.048218,-77.026434&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.063568,-77.03681&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.063568,-77.03681&amp;aq=&amp;sll=-12.048218,-77.026434&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.063568,-77.03681" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Museo Metropolitano de Lima.jpg', 'habilitado'),
(13, 1, 'Museo Numismático del Perú', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Junín 871 (Tribunal de Cuentas)', '', 'Ingreso Libre', '613200 Anexo 5951', 'museo@bcrp.gob.pe', 'http://www.viabcp.com/zona_publica/04_banco/index.asp?SEC=4&JER=1845', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.049215,-77.024136&amp;aq=&amp;sll=-12.063568,-77.03681&amp;sspn=0.011016,0.01869&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.049215,-77.024136&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.049215,-77.024136&amp;aq=&amp;sll=-12.063568,-77.03681&amp;sspn=0.011016,0.01869&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.049215,-77.024136" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Museo Numismático del Perú.jpg', 'habilitado'),
(14, 1, 'Museo Taurino Plaza de Toros Acho', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Hualgayoc 332', 'Lu-Vie 8:30- 4:30', 'Nac3, Extr 5 y Niños 1', '4811467', 'emoreno@sblm.gob.pe', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.041304,-77.023238&amp;aq=&amp;sll=-12.049215,-77.024136&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.049205,-77.024138&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.041304,-77.023238&amp;aq=&amp;sll=-12.049215,-77.024136&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.049205,-77.024138&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Museo Taurino Plaza de Toros Acho.jpg', 'habilitado'),
(15, 1, 'Museo Municipal del Teatro', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Huancavelica 332', 'Martes a Domingo de 9:30 a 5:00', 'Ingreso Libre', '2098400', 'teatrosmunicipales@munlima.gob.pe', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=-12.046403,-77.035074&amp;aq=&amp;sll=-12.041314,-77.023237&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.041314,-77.023237&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=-12.046403,-77.035074&amp;aq=&amp;sll=-12.041314,-77.023237&amp;sspn=0.011017,0.01869&amp;ie=UTF8&amp;ll=-12.041314,-77.023237&amp;spn=0.011017,0.01869&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', '', ''),
(16, 1, 'Museo Panteón Nacional de los Próceres', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Parque Universitario (Casona de San Marcos)', 'Lun-Dom 10-5', 'Publico General S/.1', '4278157', 'elisa_ruavargas@yahoo.es', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=Casona+de+San+Marcos,+Parque+Universitario,+Azangaro,+Lima,+Per%C3%BA&amp;aq=0&amp;oq=Parque+Universitario+(Casona+de+San+Marcos)&amp;sll=-12.046393,-77.035081&amp;sspn=0.011017,0.01869&amp;g=-12.046403,-77.035074&amp;ie=UTF8&amp;hq=Casona+de+San+Marcos,+Parque+Universitario,+Azangaro,+Lima,+Per%C3%BA&amp;hnear=&amp;radius=15000&amp;ll=-12.054622,-77.032158&amp;spn=0.071946,0.071946&amp;t=m&amp;iwloc=lyrftr:m,17907040465394834257,-12.04805,-77.02652&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=Casona+de+San+Marcos,+Parque+Universitario,+Azangaro,+Lima,+Per%C3%BA&amp;aq=0&amp;oq=Parque+Universitario+(Casona+de+San+Marcos)&amp;sll=-12.046393,-77.035081&amp;sspn=0.011017,0.01869&amp;g=-12.046403,-77.035074&amp;ie=UTF8&amp;hq=Casona+de+San+Marcos,+Parque+Universitario,+Azangaro,+Lima,+Per%C3%BA&amp;hnear=&amp;radius=15000&amp;ll=-12.054622,-77.032158&amp;spn=0.071946,0.071946&amp;t=m&amp;iwloc=lyrftr:m,17907040465394834257,-12.04805,-77.02652" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', '', ''),
(17, 2, 'Museo Naval (sede Lima,  Casa  Grau)', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Huancavelica 172', 'Mie-Dom 9-3', 'Adulto2, Estudiante1', '4285012', 'jairomerov@hotmail.com', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps/ms?msa=0&amp;msid=205308999555247473030.0004d1c856fcd1b10da42&amp;ie=UTF8&amp;ll=-12.056444,-77.032887&amp;spn=0.027952,0.020288&amp;t=m&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps/ms?msa=0&amp;msid=205308999555247473030.0004d1c856fcd1b10da42&amp;ie=UTF8&amp;ll=-12.056444,-77.032887&amp;spn=0.027952,0.020288&amp;t=m&amp;source=embed" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', '', ''),
(18, 2, 'Museo de la Policía', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Huanta 706 (Plaza Italia) Barrios Altos, Lima.', 'Lun-Vie 9-2', 'Ingreso Libre', '4270180', 'grcalder@pucp.edu.pe', 'www.museodelapoliciadelperu.org', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?q=-12.05082,-77.022626&amp;num=1&amp;ie=UTF8&amp;ll=-12.050794,-77.022067&amp;spn=0.002754,0.004672&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?q=-12.05082,-77.022626&amp;num=1&amp;ie=UTF8&amp;ll=-12.050794,-77.022067&amp;spn=0.002754,0.004672&amp;t=m&amp;z=14&amp;source=embed" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Museo de la Policía.jpg', 'habilitado'),
(19, 6, 'Museo de Arte Religioso de la Catedral de Lima', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Carabaya s/n, Plaza Mayor', 'Mar-Dom 9-5, Sáb 10-1', 'Adulto 10. Escolar 2', '4279647', 'catedraldelima@yahoo.es', 'www.arzonispadodelima.org', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?q=-12.046734,-77.02972&amp;num=1&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.04655,-77.03006&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?q=-12.046734,-77.02972&amp;num=1&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.04655,-77.03006&amp;source=embed" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', '', ''),
(20, 6, 'Museo Cementerio Presbítero  Matías Maestro', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'El Agustino', 'Jr. Ancash 1611', 'Lun -Vie 9-4:30 pm', 'Adulto 20 Niño 10', '3852117', 'comunicaciones@sblm.gob.pe', 'http://www.agotur.com/atractive_detail.php?sub=28&id=21', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?q=-12.041458,-77.005237&amp;num=1&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.041548,-77.005121&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?q=-12.041458,-77.005237&amp;num=1&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.041548,-77.005121&amp;source=embed" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', '', ''),
(21, 6, 'Museo del Convento de Santo Domingo', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Camaná 170', 'Lun-Dom 9:30-6:30', 'Adulto 5, Univer 3, Escolar1', '7341190', 'mailto:adm.santodomingo@gmail.com', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=jir%C3%B3n+Caman%C3%A1+170&amp;aq=&amp;sll=-12.041548,-77.005121&amp;sspn=0.001619,0.002642&amp;g=-12.041458,-77.005237&amp;ie=UTF8&amp;hq=&amp;hnear=Jir%C3%B3n+Caman%C3%A1,+Lima&amp;ll=-12.049262,-77.035069&amp;spn=0.001618,0.002642&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=jir%C3%B3n+Caman%C3%A1+170&amp;aq=&amp;sll=-12.041548,-77.005121&amp;sspn=0.001619,0.002642&amp;g=-12.041458,-77.005237&amp;ie=UTF8&amp;hq=&amp;hnear=Jir%C3%B3n+Caman%C3%A1,+Lima&amp;ll=-12.049262,-77.035069&amp;spn=0.001618,0.002642&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', '', ''),
(22, 6, 'Museo Palacio Arzobispal de Lima', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Carabaya s/n, Plaza Mayor', 'Mar-Dom 9-5', 'Adulto 20, Niño Gratis', '4275790', 'palacioarzobispal@gmail.com', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?q=-12.046734,-77.02972&amp;num=1&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.04655,-77.03006&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?q=-12.046734,-77.02972&amp;num=1&amp;ie=UTF8&amp;t=m&amp;z=14&amp;ll=-12.04655,-77.03006&amp;source=embed" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', 'large/Museo Palacio Arzobispal de Lima.jpg', 'habilitado'),
(23, 6, 'Museo del Convento de Los Descalzos', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Rimac', 'Manco Cápac 202 - A', 'Mier-Lun9:30-1 y  de 2-5:30', 'Adulto 5, Est y Jub 3, Niños 2', '4810441', 'coordina@descalzosdelrimac.org', 'no abren martes', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=Alameda+De+Los+Descaizos,+Lima&amp;aq=0&amp;oq=alam&amp;sll=-12.068114,-77.028612&amp;sspn=0.001618,0.002642&amp;ie=UTF8&amp;hq=&amp;hnear=Alameda+De+Los+Descaizos,+Lima&amp;ll=-12.036029,-77.025828&amp;spn=0.001629,0.002642&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=Alameda+De+Los+Descaizos,+Lima&amp;aq=0&amp;oq=alam&amp;sll=-12.068114,-77.028612&amp;sspn=0.001618,0.002642&amp;ie=UTF8&amp;hq=&amp;hnear=Alameda+De+Los+Descaizos,+Lima&amp;ll=-12.036029,-77.025828&amp;spn=0.001629,0.002642&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', 'large/Museo del Convento de Los Descalzos.jpg', 'habilitado'),
(24, 6, 'Museo y Catacumbas del Convento  San Francisco de Asís', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Ancash  Cdra 3 y Lampa', 'Lun-Dom 9:30-5:30', 'Adulto 7Univer 3,5 y Escolar 1', '7197188', 'informes@museocatacumbas.com', 'http://www.museocatacumbas.com/index.php', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?ie=UTF8&amp;q=Convento+de+San+Francisco&amp;fb=1&amp;gl=pe&amp;hq=&amp;cid=7568394681644818117&amp;hnear=&amp;ll=-12.04534,-77.027025&amp;spn=0.006295,0.006295&amp;t=m&amp;iwloc=lyrftr:m,7568394681644818117,-12.045341,-77.027024&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?ie=UTF8&amp;q=Convento+de+San+Francisco&amp;fb=1&amp;gl=pe&amp;hq=&amp;cid=7568394681644818117&amp;hnear=&amp;ll=-12.04534,-77.027025&amp;spn=0.006295,0.006295&amp;t=m&amp;iwloc=lyrftr:m,7568394681644818117,-12.045341,-77.027024&amp;source=embed" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', 'large/Museo y Catacumbas del Convento  San Francisco de Asís.jpg', 'habilitado'),
(25, 3, 'Museo de Sitio Parque de la Muralla', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', ' Jr. Lampa cdra. 1 y Amazonas.', 'Lunes a viernes de 10 a.m. a 7 p.m. / Sabado y Domingo  de 10 a.m. a 8 p.m.', 'Entrada general: S/.1', '4331635', 'jlerrea@hotmail.com', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=Parque+De+La+Muralla,+Lima&amp;aq=0&amp;oq=parque+de+la+muralla+&amp;sll=-12.033825,-77.024814&amp;sspn=0.001629,0.002642&amp;ie=UTF8&amp;hq=&amp;hnear=&amp;ll=-12.047054,-77.010655&amp;spn=0.006295,0.006295&amp;t=m&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=Parque+De+La+Muralla,+Lima&amp;aq=0&amp;oq=parque+de+la+muralla+&amp;sll=-12.033825,-77.024814&amp;sspn=0.001629,0.002642&amp;ie=UTF8&amp;hq=&amp;hnear=&amp;ll=-12.047054,-77.010655&amp;spn=0.006295,0.006295&amp;t=m" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', '', ''),
(26, 3, 'Museo de Antropología, Arqueología e Historia (UNFV)', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Av. Nicolás de Piérola 352', 'Lun-Vie 9-1 y de 2-5', 'Ingreso Libre', '3817141', 'mpazosarq@gmail.com', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps/ms?msa=0&amp;msid=205308999555247473030.0004d1c856fcd1b10da42&amp;ie=UTF8&amp;ll=-12.056444,-77.032887&amp;spn=0.027952,0.020288&amp;t=m&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps/ms?msa=0&amp;msid=205308999555247473030.0004d1c856fcd1b10da42&amp;ie=UTF8&amp;ll=-12.056444,-77.032887&amp;spn=0.027952,0.020288&amp;t=m&amp;source=embed" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', '', 'deshabilitado'),
(27, 3, 'Museo de Arqueología Josefina Ramos de Cox', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Plaza Francia-Jr. Rufino Torrico 1164-Lima', 'Mar-Vier 9-5', 'Ingreso Libre', '6266600', 'iaguila@pucp.edu.pe; majrc@pucp.edu.pe', 'http://www.pucp.edu.pe/ira/?museo_arqueo_pres.htm', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=Plaza+Francia,+Jir%C3%B3n+Rufino+Torrico,+Lima,+Per%C3%BA&amp;aq=0&amp;oq=plaza+franc&amp;sll=-12.052751,-77.037651&amp;sspn=0.001214,0.001786&amp;ie=UTF8&amp;hq=Plaza+Francia,+Jir%C3%B3n+Rufino+Torrico,+Lima,+Per%C3%BA&amp;ll=-12.053249,-77.037768&amp;spn=0.006295,0.006295&amp;t=m&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=Plaza+Francia,+Jir%C3%B3n+Rufino+Torrico,+Lima,+Per%C3%BA&amp;aq=0&amp;oq=plaza+franc&amp;sll=-12.052751,-77.037651&amp;sspn=0.001214,0.001786&amp;ie=UTF8&amp;hq=Plaza+Francia,+Jir%C3%B3n+Rufino+Torrico,+Lima,+Per%C3%BA&amp;ll=-12.053249,-77.037768&amp;spn=0.006295,0.006295&amp;t=m" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', '', ''),
(28, 3, 'Museo de Arqueología y Antropología ( UNMSM)', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Av. Nicolás de Piérola 1222', 'Lun-Vie 10-1 y de 2-5', 'Ingreso Libre', '6197000', 'museoarql.ccsm@unmsm.edu.pe', 'http://www.ccsm-unmsm.edu.pe/arqueologia/E32', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=Av.+Nicol%C3%A1s+de+Pi%C3%A9rola+1222&amp;aq=&amp;sll=-12.044685,-77.026335&amp;sspn=0.001618,0.002642&amp;ie=UTF8&amp;hq=&amp;hnear=Avenida+Nicol%C3%A1s+de+Pi%C3%A9rola+1222,+Lima&amp;ll=-12.05293,-77.032568&amp;spn=0.001618,0.002642&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=Av.+Nicol%C3%A1s+de+Pi%C3%A9rola+1222&amp;aq=&amp;sll=-12.044685,-77.026335&amp;sspn=0.001618,0.002642&amp;ie=UTF8&amp;hq=&amp;hnear=Avenida+Nicol%C3%A1s+de+Pi%C3%A9rola+1222,+Lima&amp;ll=-12.05293,-77.032568&amp;spn=0.001618,0.002642&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', '', ''),
(29, 3, 'Museo de Artes y Tradiciones Populares del IRA de la PUCP', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Camaná 459', 'Lun-Vier 10-1 y de 2-7', 'Adulto 2, Niños, Est Y', '6266600', 'matp@pucp.edu.pe; cmmendoza@pucp.edu.pe; lrepetto@pucp.edu.pe', 'http://www.pucp.edu.pe/ira/C32', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=459+Caman%C3%A1,+Lima&amp;aq=0&amp;oq=Caman%C3%A1+459&amp;sll=-12.055644,-77.036562&amp;sspn=0.001618,0.002642&amp;ie=UTF8&amp;hq=&amp;hnear=Camana&amp;ll=-12.055731,-77.036691&amp;spn=0.001618,0.002642&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=459+Caman%C3%A1,+Lima&amp;aq=0&amp;oq=Caman%C3%A1+459&amp;sll=-12.055644,-77.036562&amp;sspn=0.001618,0.002642&amp;ie=UTF8&amp;hq=&amp;hnear=Camana&amp;ll=-12.055731,-77.036691&amp;spn=0.001618,0.002642&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', '', ''),
(30, 3, 'Museo Etnográfico Amazónico del Centro Cultural "José Pío Aza"', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Callao 562', 'Lun-Vier 9-5', 'Adul 2 y Est 1', '3310771', 'solidaridad@selvasperu.org; prensa@selvasperu.org; informes@selvasperu.org', 'http://www.selvasperu.org/museo_index.html', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps/ms?msa=0&amp;msid=205308999555247473030.0004d1c856fcd1b10da42&amp;ie=UTF8&amp;ll=-12.056444,-77.032887&amp;spn=0.027952,0.020288&amp;t=m&amp;output=embed"></iframe><br /><small>Ver <a href="https://maps.google.es/maps/ms?msa=0&amp;msid=205308999555247473030.0004d1c856fcd1b10da42&amp;ie=UTF8&amp;ll=-12.056444,-77.032887&amp;spn=0.027952,0.020288&amp;t=m&amp;source=embed" style="color:#0000FF;text-align:left">Atractivos Turísticos  de Lima Cercado</a> en un mapa más grande</small>', 'large/Museo Etnográfico Amazónico del Centro Cultural "José Pío Aza".jpg', 'deshabilitado'),
(31, 3, 'Museo Nacional Afroperuano', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Ancash 542', 'Lun-Vie 9-1 y 2-5', 'Ingreso Libre', '3150400', 'museonacionalafroperuano@hotmail.com', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=563+Ancash,+Lima&amp;aq=0&amp;oq=ancash+563&amp;sll=-12.042447,-77.03727&amp;sspn=0.003237,0.005284&amp;ie=UTF8&amp;hq=&amp;hnear=Ancash,+Lima&amp;ll=-12.04769,-77.019789&amp;spn=0.001629,0.002642&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=563+Ancash,+Lima&amp;aq=0&amp;oq=ancash+563&amp;sll=-12.042447,-77.03727&amp;sspn=0.003237,0.005284&amp;ie=UTF8&amp;hq=&amp;hnear=Ancash,+Lima&amp;ll=-12.04769,-77.019789&amp;spn=0.001629,0.002642&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', '', ''),
(32, 3, 'Museo Nacional de la Cultura Peruana', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Av. Alfonso Ugarte 650', 'Mar-Sáb 10-5', 'Adul 5 Est, jub, Prof 2 Esco1', '4235892', 'mncp@inc.gob.pe', 'http://museodelacultura.perucultural.org.pe/', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=650+Avenida+Alfonso+Ugarte,+Lima&amp;aq=0&amp;oq=Av.+Alfonso+Ugarte+650&amp;sll=-12.046684,-77.025922&amp;sspn=0.001629,0.002642&amp;ie=UTF8&amp;hq=&amp;hnear=Av+Alfonso+Ugarte,+Lima&amp;ll=-12.048507,-77.042478&amp;spn=0.001618,0.002642&amp;t=m&amp;z=14&amp;iwloc=lyrftr:m,9965222096221495496,-12.047877,-77.043042&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=650+Avenida+Alfonso+Ugarte,+Lima&amp;aq=0&amp;oq=Av.+Alfonso+Ugarte+650&amp;sll=-12.046684,-77.025922&amp;sspn=0.001629,0.002642&amp;ie=UTF8&amp;hq=&amp;hnear=Av+Alfonso+Ugarte,+Lima&amp;ll=-12.048507,-77.042478&amp;spn=0.001618,0.002642&amp;t=m&amp;z=14&amp;iwloc=lyrftr:m,9965222096221495496,-12.047877,-77.043042" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', '', ''),
(33, 4, 'Museo "Andrés del Castillo"', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. de la Unión 1030', 'Mier-Lun 9-6', 'Adulto 10, Ms de 60 y Univ 5', '4332831', 'museo@madc.com.pe', 'museo@madc.com.pe', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=1030+Jir%C3%B3n+de+La+Uni%C3%B3n,+Lima&amp;aq=0&amp;oq=Jr.+de+la+Uni%C3%B3n+1030&amp;sll=-12.047618,-77.043064&amp;sspn=0.001618,0.002642&amp;ie=UTF8&amp;hq=&amp;hnear=Jir%C3%B3n+de+La+Uni%C3%B3n+1030,+Lima+15001&amp;ll=-12.053517,-77.036069&amp;spn=0.001618,0.002642&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=1030+Jir%C3%B3n+de+La+Uni%C3%B3n,+Lima&amp;aq=0&amp;oq=Jr.+de+la+Uni%C3%B3n+1030&amp;sll=-12.047618,-77.043064&amp;sspn=0.001618,0.002642&amp;ie=UTF8&amp;hq=&amp;hnear=Jir%C3%B3n+de+La+Uni%C3%B3n+1030,+Lima+15001&amp;ll=-12.053517,-77.036069&amp;spn=0.001618,0.002642&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', '', ''),
(34, 4, 'Museo de Neuropatología', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr. Ancash 1271', 'Lun-Sab 8-2', 'PG 3', '4117768 Anexo 278', 'diana.rivas@laposte.net', '-', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?ie=UTF8&amp;q=Museo+de+Neuropatologia&amp;fb=1&amp;gl=pe&amp;hq=&amp;cid=4222785957348298144&amp;hnear=&amp;ll=-12.042051,-77.115173&amp;spn=0.006295,0.006295&amp;t=m&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?ie=UTF8&amp;q=Museo+de+Neuropatologia&amp;fb=1&amp;gl=pe&amp;hq=&amp;cid=4222785957348298144&amp;hnear=&amp;ll=-12.042051,-77.115173&amp;spn=0.006295,0.006295&amp;t=m&amp;iwloc=A&amp;source=embed" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', 'large/Museo de Neuropatología.jpg', 'habilitado');
INSERT INTO `museo` (`Id`, `id_categ`, `Nombre`, `acerca`, `Ubicacion`, `Direccion`, `Horario`, `Costo`, `Telefono`, `Correo`, `Web`, `url`, `imagen`, `estado`) VALUES
(35, 5, 'Museo de Arte de Lima (MALI)', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Paseo Colón 125', 'Mar -Dom 10-8, Sáb 10-5', 'Dom 1', '4234732', 'informes@mali.pe', 'http://museoarte.perucultural.org.pe/', '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.pe/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=125+Paseo+Colon,+Lima&amp;aq=0&amp;oq=Paseo+Col%C3%B3n+125&amp;sll=-12.042051,-77.115172&amp;sspn=0.001619,0.002642&amp;gl=pe&amp;ie=UTF8&amp;hq=&amp;hnear=Paseo+Colon,+Lima&amp;ll=-12.060138,-77.039087&amp;spn=0.001629,0.002642&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.pe/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=125+Paseo+Colon,+Lima&amp;aq=0&amp;oq=Paseo+Col%C3%B3n+125&amp;sll=-12.042051,-77.115172&amp;sspn=0.001619,0.002642&amp;gl=pe&amp;ie=UTF8&amp;hq=&amp;hnear=Paseo+Colon,+Lima&amp;ll=-12.060138,-77.039087&amp;spn=0.001629,0.002642&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>', '', ''),
(36, 5, 'Museo de Arte Italiano de Lima', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Paseo de la República 250', 'Mar-Dom 10-5', 'Adul 5, Uni2 Esc 1', '4239932', 'museodearteitaliano@mcultura.gob.pe', '-', '', 'large/Museo de Arte Italiano de Lima.jpg', 'habilitado'),
(37, 5, 'Museo de Arte de la UNMSM', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Av. Nicolás de Piérola 1222, Cercado', 'Lun-Vie 10-1 y de 2-5', 'Ingreso Libre', '6197000 Anexo 5204', 'museoarte.ccsm@unmsm.edu.pe', 'http://www.ccsm-unmsm.edu.pe/arte/H40', '', '', ''),
(38, 5, 'Museo del Banco Central de Reserva del Perú', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Esquina Jr. Ucayali 271 y Jr. Lampa', 'Mar -Vie 10-4:30 Sáb y Dom 10-1', 'Ingreso Libre', '6132000 Anexo 2655', 'marialuisa.zuniga@bcrp.gob.pe', 'http://www.bcrp.gob.pe/proyeccion-institucional/museo.', '', '', ''),
(39, 5, 'Pinacoteca Ignacio Merino', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Centro Histórico de Lima', 'Jr.Conde de Superunda 141 (Palacio Municipal)', 'Lun-Vier 8:30-4', 'Ingreso Libre', '3151539', 'pinacoteca@munlima.gob.pe', '-', '', '', ''),
(40, 5, 'Casa Museo Ricardo Palma', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'General Suárez 189  Miraflores', 'Lun-Vier: 9:30 - 5', 'PG 6 Y Est y Júb 3', '4455836', 'lacasade.ricardopalma@gmail.com', 'http://ricardopalma.miraflores.gob.pe/', '', '', ''),
(41, 5, 'Museo Compañia de Bomberos Voluntarios "Italia N5"', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Facultad de Ingeniería de Minas PUCP Av. Universitaria 101San Miguel', 'Lun-Sáb 9-5', 'Ingreso Libre', '4290318', '', 'museobomberos.perucultural.org.pe/', '', '', ''),
(42, 5, 'Museo de la Inmigración Japonesa', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av. Gregorio Escobedo 803 Jesús María', 'Lun-Vier 10-6', 'Ingreso Libre', '518 74 50 Anexo 1031', 'muse@apj.org.pe', 'http://www.facebook.com/pages/Museo-de-la-Inmigración-Japonesa-al-Perú-Carlos-Chiyoteru-Hiraoka/169670499806554', '', '', ''),
(43, 5, 'Museo Aeronáutico', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Base Aerea Las Palmas, Surco', 'Lunes a Viernes de :8-1 y de 2-4', '-', '213-5200 Anexo 6005', 'museo_fap@fap.mil.pe', 'http://www.incaland.com/MuseoFAP/BIENVENIDA.htm', '', '', ''),
(44, 5, 'Museo Andrés Avelino Cáceres', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Parque ReductoN 02 Ramón Ribeyro 401 Miraflores', 'Lun-Sab 10-5', 'Adulto 5, Est 2', '6177279', 'luisgraga@hotmail.com', '-', '', '', ''),
(45, 5, 'Museo Complejo Histórico Benemérita Guardia Civil del Perú', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Calle Mayor GC BernardoBalaguer Morales s/n(km.19,5 Carretera Central) Ñana Chaclacayo Chaclacayo', 'Lun-Vier 10-5', 'Adulto 10, Niño 6', '359 34 39', 'ricardopiscontemartinez@hotmail.com', '-', '', '', ''),
(46, 5, 'Museo del Ejército Fortaleza del Real Felipe', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Plaza Independencia Callao', 'Lun -Dom9-2', 'Extra 12, Adut 6, Niño 3', '4290532', 'jacintoramirez@hotmail.com-fortalezadelrealfelipe@hotmail.com', '-', '', '', ''),
(47, 5, 'Museo Monumento al Valor Militar Chavín de Huántar', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Ca. Camino Real con Av. Las Palmas s/n -Chorrillos', 'Lun-Sáb 9-3', 'Gratuito', '2523541', '', '-', '', '', ''),
(48, 5, 'Museo Naval del Perú', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Jirón José Galvez123 Callao', 'Mar-Dom 9-2', 'Adulto 3, Niño 2', '4294793 Anexo 6794', 'informes@museonaval.com.pe', '-', '', '', ''),
(49, 5, 'Museo de sitio Submarino Abtao', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av. Jorge Chávez120 A Callao', 'Mar-Dom 9:30-4:30', 'Adulto 10, Niño 5', '7956900', 'museo.abtao@hotmail.com', '-', '', '', ''),
(50, 5, 'Museo de Sitio de Ancón', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Prolongación Jorge Chávez s/n- Ancon', 'Lun-Dom 8-1y de 2-6', 'EG1', '5521162', 'museodeancon@hotmail.com-justo.caceres@hotmail.com', '-', '', '', ''),
(51, 5, 'Museo de Sitio Arturo Jiménez Borja -Puruchuco', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Puruchuco Carretera Central, km 4,5 Ate', 'Mar-Dom 9-4', 'Adulto y Extr5, Uni y prof 2, Esc1', '4942641', 'museopuruchuco@mcultura.gob.pe', '-', '', '', ''),
(52, 5, 'Museo de Sitio Ernest W.Middendorf', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av. Las Leyendas 500 Parque de las Leyendas San Miguel', 'Previo pago el parque de las leyendas', '', '719 2879', 'lucenida.carrion@leyendas.gop.pe', '-', '', '', ''),
(53, 5, 'Museo de Sitio Huaca Pucllana', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'General Borgoño cuadra 8 s/n.Miraflores', 'Mar-Dom9-5', 'Adulto12, Univ y prof5, Esco y Jub 1', '6177148', 'huacapucllana@hotmail.com', '-', '', '', ''),
(54, 5, 'Museo de Sitio Huallamarca', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'NicolásdeRibera 201  San Isidro', 'Mar-Dom9-6', 'Adulto5,Uni, Pro y Jub 3, Esco  1', '', 'museohuallmarca@mcultura.gob.pe', '-', '', '', ''),
(55, 5, 'Museo de sitio Pachacamac', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'km.31.5 de la antigua PanamericanaSur Lurín', 'Mar-Sáb9-5', 'Adulto 8, Est, Prof y Jub 4, Esc1', '4302115', 'dbozzi@mcultura.gob.pe', '-', '', '', ''),
(56, 5, 'Fundación Museo Amano', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Calle Retiro 160 Miraflores', 'Lun-Vie (3,4 y5 previa cita)', 'Contribución voluntaria', '4412909', 'museo@fundacionmuseoamano.org.pe', '-', '', '', ''),
(57, 5, 'Museo Nacional de Antropología, Biodiversidad, Agricultura y Alimentación (UNALM)', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Ca. Camilo Carrillo 325-A', 'Lun-Vie8:30-12:30 y de 2-3:30', '-', '4250961', 'museodeantropologia@lamolina.edu-pe', '-', '', '', ''),
(58, 5, 'Museo Colli', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Pasaje Libertad Lote 5, Mza LL de la 3ra Zona  de Collique - Comas', 'Lun-Dom8-4', '-', '5202348', 'niquin1951@gmail.com', '-', '', '', ''),
(59, 5, 'Museo Larco', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av. Bolívar 1515 Pueblo Libre', 'Lun-Dom9-10', 'Adulto30, Adult mayor 25, Estudiante15', '4611312', 'webmaster@museolarco.org', 'http://www.museolarco.org/', '', '', ''),
(60, 5, 'Museo Victoria Chi Fu de Lam', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Colegio peruano chibo Juan XXIII, Jr. Castilla 842- San Miguel', 'Lun-Vier8-3:30', '….', '6142323', 'juan23@juan23.edu.pe', 'MUSEO NO ABIERTO PARA EL PÚBLICO', '', '', ''),
(61, 5, 'Museo Antonio Raimondi', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av La Fontana 755 La Molina', 'Lun-Vier8-4', 'Previa cita, gratuito', '614 9700 Anexo 132', 'lfvillacorta@raimondi.edu.pe', 'www.museoraimondi.org.pe', '', '', ''),
(62, 5, 'Museo Regional de Arqueología, Antropología e Historia Juan José Vega Tello', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Kilomtro 25.2 CARRETERA Lima -Canta Carabayllo', 'Lun-Dom9-4', 'Adulto 3, Niños 2', '7935123', 'colliruna@hotmail.com', '-', '', '', ''),
(63, 5, 'Museo de la Nación', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av. Javier Prado Este 24 65 San Borja', 'Mar-Dom9-5', '', '4769933', 'mnacion@mcultura.gob.pe', '-', '', '', ''),
(64, 5, 'Museo Nacional de Arqueología, Antropología e Historia del Perú', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Plaza Bolívar s/n  Pueblo Libre', 'Mar-Sáb9-5, Dom 9-4', 'Adulto10, Uniy Júb 5 Esc2', '4635070', 'andresac@museolarco.org', '-', '', '', ''),
(65, 5, 'Museo de Oro y Armas del Mundo', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av. Alonso de Molina 1100 Surco', 'Lun-Dom 10:30-6', 'Adultos33,Niños menores de 11 años 16', '3451271', 'info@museoroperucom.pe', '-', '', '', ''),
(66, 5, 'Asociación Museo del Automóvil', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av. La Molina Cuadra 9. Urbanización el Sol de la Molina. La Molina', 'Lun-Dom 9:30-7', 'Adulto 20, Niños 10', '3680373', 'jnicolini@infonegocios.com', 'www.museodelautomovilnicolini.com', '', '', ''),
(67, 5, 'Museo de la Electricidad', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av. Pedro de Osma 105 Barranco', 'Lun-Dom 9-5', 'Gratuito', '4776577', 'museoelectri@speedy.com.pe', '-', '', '', ''),
(68, 5, 'Museo de Entomología Klaus Raven (UNALM)', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Universidad Nacional Agraria Av. La Universidad s/n. La Molina', '', 'Entrada G 5 Esc 3', '6147800 Anexo 300', 'museo@ciaraimondi.edu.pe', 'www.lamolina.edu.pe', '', '', ''),
(69, 5, 'Museo Geológico y Panteológico', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av. Tupac Amaru210 (km.4.5) Rímac', 'Lun-Vier 9-4, previa cita', 'Est estatal 1, est parti y pg3', '3822174', 'www.uni.edu.pe', '-', '', '', ''),
(70, 5, 'Museo George Petersen (PUCP)', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Facultad de Ingeniería de Minas PUCP Av. Universitaria 101San Miguel', 'Lun-Vier 8-1 de 2-5', 'Gratuito', '626000', 'www.pucp.edu.pe', '-', '', '', ''),
(71, 5, 'Museo de Historia Natural', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'UNMSM Av. Arenales 1256 Jesús María', 'Lun-Sáb9-5 y de Dom-10-2', 'Adulto7, Niño5, Serv Guiado25', '2656819', '', '-', '', '', ''),
(72, 5, 'Museo de Historia Natural Vera Alleman (URP)', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Universidad Ricardo Palma Av. Benavides 5440 Surco', 'Lun-Vier9-4', 'Público 7, Est 5', '7080000 Anexo 2271', 'mhn-urp@urp.edu.pe', '-', '', '', ''),
(73, 5, 'Museo Histórico de Ciencias Físicas', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av. Venezuela cuadra 34 (ambientes 306-307-308)Tercer piso facultad de ciencias Físicas)UNMSM', 'Lun-Vier 9-1', 'Alumnos 5, Inst del Estado 3', '619 7000 Anexo 3809', 'mhcf@unmsm.edu.pe', '-', '', '', ''),
(74, 5, 'Museo del Petroleo', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Parque de las Leyendas Av. Las Leyendas 500 San Miguel', '-', 'Leyendas: adulto 10, niño 5', '945142706', 'relacionescorporativas@petroperu.com.pe / xpoblet@petroperu.com.pe', '-', '', '', ''),
(75, 5, 'Museo de Arte Colonial Pedro de Osma', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av. Pedro de Osma 421 Barranco', 'Mar-Dom 10-6', 'General20, Est y adulto mayor10', '4670141', 'museo@fudacionosa.org', 'www.museopedrodeosma.org.pe', '', '', ''),
(76, 5, 'Museo de Arte Contemporaneo de Lima', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av Grau 1511- Barranco', 'Mar-Dom9-7', 'Ingreso Libre', '4670141', 'contacto@mac-lima.org.pe/arocarey@mac-lima.org.pe', 'http://mac-lima.org.pe', '', '', ''),
(77, 5, 'Museo Capitàn de Navío Juan Faninning García', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Base d eInfantería de Ancón', '-', '-', '4883242', '-', '-', '', '', ''),
(78, 5, 'Museo de Antropología y Agricultura prehispánica', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Centro de investigaciones de zonas áridas - Calle CamiloCarrillo 325-A Jesús María', 'Lun-Vier 9-5:15, Sáb 9-4:30, Dom 10-1:30', 'Adulto 7, Niñ y Est5', '4710117', '-', '-', '', '', ''),
(79, 5, 'Parque de la Imaginación', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av. Riva Agüero s/ncuadra 8 San Miguel', 'Temporalmente cerrado', '-', '6281804', 'informes@parquedelaimaginacion.com', '-', '', '', ''),
(80, 5, 'Museo de Arte Fernando Saldias', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Av.Petit  Touars 2399 Lince', 'Lun-Vier 6-9', 'Adulto 20, Jub Niñ y Est 10', '422 6749', 'aureiperu@gmail.com', 'http://artistasplasticosperu.blogspot.com/2010/10/inauguracion-del-museo-de-arte-fernando.html', '', '', ''),
(81, 5, 'Museo Manos Peruanas', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Comandante Juan More 199 Miraflores', 'Lun-Vier10-5', '-', '4466951', 'manosperuanas@raymisa.com', 'http://www.raymisa.com', '', '', ''),
(82, 5, 'Museo Santuario Coronel Leoncio Prado', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Colegio Militar Leoncio PradoAv. Costanera 1545 La Perla', '-', '-', '4204118', '', '', '', '', ''),
(83, 5, 'Museo de Sitio Alejandro Miro Quesada Garland', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. Sed eleifend nonummy diam. Praesent mauris ante, elementum et , bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. Suspendisse vulputate aliquam dui.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'Lima Metropolitana', 'Prolongación Jorge Chavez s/n-Ancón', '-', '-', '5521162', 'museodeancon@hotmail.com', 'http://www.museodeancon.com/', '', '', '');

-- --------------------------------------------------------

--
-- Table structure for table `usuario`
--

CREATE TABLE IF NOT EXISTS `usuario` (
  `id_usuario` int(11) NOT NULL AUTO_INCREMENT,
  `user_nombres` varchar(50) NOT NULL,
  `user_apellidos` varchar(50) NOT NULL,
  `user_direccion` varchar(50) DEFAULT NULL,
  `user_username` varchar(20) NOT NULL,
  `user_password` varchar(250) NOT NULL,
  `user_tipo` varchar(20) NOT NULL,
  `user_nivel` varchar(20) NOT NULL,
  `user_dni` varchar(8) NOT NULL,
  `user_email` varchar(50) NOT NULL,
  `user_telefono` varchar(15) DEFAULT NULL,
  `user_celular` varchar(15) NOT NULL,
  PRIMARY KEY (`id_usuario`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

--
-- Dumping data for table `usuario`
--

INSERT INTO `usuario` (`id_usuario`, `user_nombres`, `user_apellidos`, `user_direccion`, `user_username`, `user_password`, `user_tipo`, `user_nivel`, `user_dni`, `user_email`, `user_telefono`, `user_celular`) VALUES
(2, 'admin', 'soporte', 'mi casa 234', 'admin', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220', 'soporte', 'superadmin', '42822312', 'soporte@smartgamers.com,pe', '1232112', '979711744');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
